### ISSUE TITLE
Disa shtesa per adset qe perdoren faqet shqiptare 

### ISSUE THREAD

**Issue by diekaines** [AnXh3L0/blocklist#5]
Pershendetje

Disa URL te kompanive te reklamave te cilat perdoren nga faqe te ndryshme shqiptare qe mund t`i shtosh ne liste.

ads.balkanweb.com
abingmedia.com
medium.al
mediadesk.al
boost.al

FLM

**Comment by AnXh3L0** [comment]
Pershendetje, faleminderit per issue-n qe hapet. Do i testoj keto domaine ne rast se prishin funksionalitet e faqeve, nese jo, do i shtoj ne liste.

**Comment by diekaines** [comment]
No problem. Per pak me shume sqarim faqet qe perdorin ato jane :

```
https://joq-albania.com/
https://www.balkanweb.com/
https://www.tpz.al/
https://www.gazetatema.net/
https://newsbomb.al/
https://tvklan.al/
http://gazetashqiptare.al/
```

Mund te kete e te tjera por kaq kam arritur te gjej/shikoj per momentin 

Tung

**Comment by AnXh3L0** [comment]
Shumica e reklamave jane tashme te mbuluara nga kjo liste, nese hasen te reja do te bllokohen. Faleminderit @diekaines .

**Comment by diekaines** [comment]
Hallall
Rrofsh
